import Ionicons from '@expo/vector-icons/Ionicons';
import { StyleSheet, Image, Platform } from 'react-native';

import { Collapsible } from '@/components/Collapsible';
import { ExternalLink } from '@/components/ExternalLink';
import ParallaxScrollView from '@/components/ParallaxScrollView';
import { ThemedText } from '@/components/ThemedText';
import { ThemedView } from '@/components/ThemedView';
import { Children } from 'react';
import { Link } from 'expo-router';

export default function TabTwoScreen() {
    const List = [
        {
            name: "Listen to Words",
            path: "Listening/words"
        },
        {
            name: "Listen to Sentences",
            path: "Listening/sentences"
        }


    ]
    return (
        <ParallaxScrollView
            headerBackgroundColor={{ light: '#D0D0D0', dark: '#353636' }}
            headerImage={<Image
                src="https://www.freepik.com/free-vector/blog-post-concept-illustration_5202424.htm#fromView=search&page=1&position=4&uuid=a78b9458-d8c3-4d7c-b11c-cd6874ae8ca5"
                style={{
                    width: 400, height: 400
                }}
            />}>
            <ThemedView style={styles.titleContainer}>
                <ThemedText type="title">Listen</ThemedText>
            </ThemedView>
            <ThemedText>Listen to words and sentences generated by AI and improve your Pronunciations</ThemedText>
            <ThemedText className="mt-4" type="subtitle">Choose:</ThemedText>
            {List.map((item, index) => {

                return (
                    <Link href={{
                        pathname: item.path,
                        params: { name: item.name }
                    }}>
                        <ThemedText type="link">{item.name}</ThemedText>
                    </Link>
                )
            })}
        </ParallaxScrollView>
    );
}


const styles = StyleSheet.create({
    headerImage: {
        color: '#808080',
        bottom: -90,
        left: -35,
        position: 'absolute',
    },
    titleContainer: {
        flexDirection: 'row',
        gap: 8,
    },
});
